OPENPITON_IC_VERILOG_RTLDIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))

ifneq (1,$(RULES))

ifeq (,$(findstring $(OPENPITON_IC_VERILOG_RTLDIR),$(MKDV_INCLUDED_DEFS)))
MKDV_INCLUDED_DEFS += $(OPENPITON_IC_VERILOG_RTLDIR)
MKDV_VL_INCDIRS += $(OPENPITON_IC_VERILOG_RTLDIR)/chipset
MKDV_VL_INCDIRS += $(OPENPITON_IC_VERILOG_RTLDIR)/chipset/include
MKDV_VL_INCDIRS += $(OPENPITON_IC_VERILOG_RTLDIR)/include
endif

else # Rules

endif